// Copyright (c) Bravellian
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

namespace Bravellian.Generators.SqlGen.Pipeline;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Humanizer;
using Bravellian.Generators.SqlGen.Common.Configuration;
using Bravellian.Generators.SqlGen.Pipeline._3_CSharpTransformation.Models;

/// <summary>
/// Generator for database context classes based on entity definitions.
/// </summary>
public class DbContextGenerator
{
    private readonly SqlConfiguration config;
    private readonly IBvLogger logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="DbContextGenerator"/> class.
    /// Creates a new instance of the DbContextGenerator.
    /// </summary>
    /// <param name="config">The SQL generation configuration.</param>
    /// <param name="logger">The logger to use for messages.</param>
    public DbContextGenerator(SqlConfiguration config, IBvLogger logger)
    {
        this.config = config ?? throw new ArgumentNullException(nameof(config));
        this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <summary>
    /// Generates a DbContext class for the specified tables.
    /// </summary>
    /// <param name="tables">The tables to include in the DbContext.</param>
    /// <param name="dbContextName">The name of the DbContext class.</param>
    /// <returns>The generated DbContext source code.</returns>
    public string GenerateDbContext(IEnumerable<ClassModel> tables, string dbContextName)
    {
        if (!this.config.GenerateDbContext)
        {
            this.logger.LogMessage($"Skipping DbContext generation because GenerateDbContext is false.");
            return string.Empty;
        }

        this.logger.LogMessage($"Generating DbContext '{dbContextName}'...");

        var sb = new StringBuilder();

        // Add file header
        sb.AppendLine("// CONFIDENTIAL - Copyright (c) Bravellian LLC. All rights reserved.");
        sb.AppendLine("// See NOTICE.md for full restrictions and usage terms.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by Bravellian.Generators.SqlGen");
        sb.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Add namespace declaration
        sb.AppendLine($"namespace {this.config.Namespace};");
        sb.AppendLine();

        // Add using statements
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();

        // Start class definition
        sb.AppendLine($"public partial class {dbContextName} : {this.config.DbContextBaseClass}<{dbContextName}>");
        sb.AppendLine("{");

        // Constructor
        sb.AppendLine($"    public {dbContextName}(DbContextOptions options)");
        sb.AppendLine($"        : base(options)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Find entity names that are duplicated across different schemas.
        var duplicateEntityNames = tables
            .GroupBy(t => t.Name, StringComparer.Ordinal)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToHashSet(StringComparer.Ordinal);

        // DbSet properties
        foreach (var table in tables.OrderBy(t => t.Name, StringComparer.Ordinal).ThenBy(t => t.SourceSchemaName, StringComparer.Ordinal))
        {
            var entityName = this.GetEntityName(table);
            var propertyName = entityName;

            // If the entity name is used by more than one table, prefix the property name
            // with the schema to avoid conflicts.
            if (duplicateEntityNames.Contains(entityName))
            {
                propertyName = $"{table.SourceSchemaName.Pascalize()}_{entityName}";
            }

            sb.AppendLine($"    public virtual DbSet<{table.SourceSchemaName.Pascalize()}.{entityName}> {propertyName} {{ get; set; }} = null!;");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private string GetEntityName(ClassModel table)
    {
        // This should match the naming logic used in the entity generator
        return table.Name;
    }
}
